# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install .

script:
  # each module should be completely covered by its test suite
  - py.test --cov rumble/adaptiverun.py tests/test_adaptiverun.py; coverage report --show-missing --fail-under=100
  - py.test --cov rumble/report.py tests/test_report.py && coverage report --show-missing --fail-under=100
  - py.test --cov rumble/rumble.py tests/test_rumble.py && coverage report --show-missing --fail-under=100
  - py.test --cov rumble/utils.py tests/test_utils.py && coverage report --show-missing --fail-under=100

  # actually run tests and generate final coverage report
  - py.test --cov rumble && coverage report --show-missing --fail-under=100

  # also sure none of the examples die
  - python examples/example.py
  - python examples/primeexample.py
  - python examples/classexample.py
  - python examples/multiargsexample.py

after_success: coveralls
deploy:
  provider: pypi
  user: mambocab
  password:
    secure: IvVB8f5Mkuqe0yqE1hEF+MSa3MFJPIwocINYw6U9Xb/DpgjeQyysAbJhRpwcIVIUzP7ZH48HM/G0Y+AnK/4mt5DtXVT5MZogmym5nfcqLPaESdinbtuySeJ5wmD0FvnDAcb0WCQQxJrn8oAK8gAeQZB42579YUAt1l+vu2Ij7iw=
  on:
    tags: true
    repo: mambocab/rumble
    branch: master
