# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  # each module should be completely covered by its test suite
  - py.test --cov rumble/adaptiverun.py tests/test_adaptiverun.py; coverage report --show-missing --fail-under=100
  - py.test --cov rumble/report.py tests/test_report.py && coverage report --show-missing --fail-under=100
  - py.test --cov rumble/stimeit.py tests/test_stimeit.py && coverage report --show-missing --fail-under=100
  - py.test --cov rumble/utils.py tests/test_utils.py && coverage report --show-missing --fail-under=100
  # make sure none of the examples die
  - python examples/example.py
  - python examples/primeexample.py
  - python examples/classexample.py
  - python examples/multiargsxample.py
  # finally, actually run tests
  - py.test --cov rumble && coverage report --show-missing --fail-under=100

after_success: coveralls
